apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-postgresql
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: django-postgresql
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: django/postgresql
        property: username

    - secretKey: password
      remoteRef:
        key: django/postgresql
        property: password

    - secretKey: database
      remoteRef:
        key: django/postgresql
        property: database

    - secretKey: host
      remoteRef:
        key: django/postgresql
        property: host

    - secretKey: port
      remoteRef:
        key: django/postgresql
        property: port
