image:
  repository: "034255117140.dkr.ecr.eu-central-1.amazonaws.com/django-app"
  tag: 25
  pullPolicy: Always

replicaCount: 1

containerPort: 8000

postgresql:
  enabled: true

  primary:
    networkPolicy:
      enabled: true
      allowExternal: false
      extraIngress:
        - ports:
            - port: 5432
          from:
            - podSelector:
                matchLabels:
                  app: django-app

  image:
    tag: latest
  auth:
    username: django
    password: django_password
    database: django_db

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
