replicaCount: 1

image:
  repository: "034255117140.dkr.ecr.eu-central-1.amazonaws.com/django-app"
  tag: "latest"
  pullPolicy: Always

django:
  debug: "True"
  allowedHosts: "*"
  secretKey: "change-me-production-secret"

db:
  name: "postgres"
  user: "postgres"
  password: "change-me-db-password"
  host: "dev-django-db-rds.ctskymysi6zv.eu-central-1.rds.amazonaws.com"
  port: "5432"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80