image:
  repository: "034255117140.dkr.ecr.eu-central-1.amazonaws.com/django-app"
  tag: 24
  pullPolicy: Always

replicaCount: 1

containerPort: 8000

postgresql:
  enabled: true
  image:
    tag: latest
  auth:
    username: django
    password: django_password
    database: django_db
