apiVersion: apps/v1
kind: Deployment

metadata:
  name: django-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: django-app

  template:
    metadata:
      labels:
        app: django-app

    spec:
      containers:
      - name: django-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: {{ .Values.containerPort }}

        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "core.settings"

        - name: DB_HOST
          value: "{{ .Release.Name }}-postgresql"

        - name: DB_NAME
          value: "{{ .Values.postgresql.auth.database }}"

        - name: DB_USER
          value: "{{ .Values.postgresql.auth.username }}"

        - name: DB_PASSWORD
          value: "{{ .Values.postgresql.auth.password }}"

        - name: DB_PORT
          value: "5432"
